"""third version

Revision ID: 73f591ad58e6
Revises: 8d188b21999d
Create Date: 2025-04-20 14:24:59.044256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73f591ad58e6'
down_revision: Union[str, None] = '8d188b21999d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('distribution', sa.String(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('kitchen_config_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['kitchen_config_id'], ['kitchen_config.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignments_distribution'), 'assignments', ['distribution'], unique=False)
    op.create_index(op.f('ix_assignments_id'), 'assignments', ['id'], unique=False)
    op.create_table('pdf_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('generated_at', sa.Date(), nullable=True),
    sa.Column('kitchen_config_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['kitchen_config_id'], ['kitchen_config.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pdf_reports_file_path'), 'pdf_reports', ['file_path'], unique=False)
    op.create_index(op.f('ix_pdf_reports_id'), 'pdf_reports', ['id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('suggestion', sa.String(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('kitchen_config_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['kitchen_config_id'], ['kitchen_config.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_recommendations_suggestion'), 'recommendations', ['suggestion'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendations_suggestion'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_pdf_reports_id'), table_name='pdf_reports')
    op.drop_index(op.f('ix_pdf_reports_file_path'), table_name='pdf_reports')
    op.drop_table('pdf_reports')
    op.drop_index(op.f('ix_assignments_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_distribution'), table_name='assignments')
    op.drop_table('assignments')
    # ### end Alembic commands ###
