"""second version

Revision ID: 8d188b21999d
Revises: 6156c0ef3cbc
Create Date: 2025-04-20 14:11:08.893634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d188b21999d'
down_revision: Union[str, None] = '6156c0ef3cbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('equipment_items_kitchen_config_id_fkey', 'equipment_items', type_='foreignkey')
    op.create_foreign_key(None, 'equipment_items', 'kitchen_config', ['kitchen_config_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'equipment_items', type_='foreignkey')
    op.create_foreign_key('equipment_items_kitchen_config_id_fkey', 'equipment_items', 'kitchen_type', ['kitchen_config_id'], ['id'])
    # ### end Alembic commands ###
