"""first version

Revision ID: f9ffb8c2ed83
Revises: 
Create Date: 2025-04-20 12:48:50.611876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9ffb8c2ed83'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kitchen_type',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kitchen_type_id'), 'kitchen_type', ['id'], unique=False)
    op.create_index(op.f('ix_kitchen_type_type'), 'kitchen_type', ['type'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_table('kitchen_config',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('area', sa.Float(), nullable=False),
    sa.Column('num_stations', sa.Integer(), nullable=False),
    sa.Column('staff_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('kitchen_type_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['kitchen_type_id'], ['kitchen_type.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kitchen_config_id'), 'kitchen_config', ['id'], unique=False)
    op.create_index(op.f('ix_kitchen_config_name'), 'kitchen_config', ['name'], unique=False)
    op.create_index(op.f('ix_kitchen_config_notes'), 'kitchen_config', ['notes'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kitchen_config_notes'), table_name='kitchen_config')
    op.drop_index(op.f('ix_kitchen_config_name'), table_name='kitchen_config')
    op.drop_index(op.f('ix_kitchen_config_id'), table_name='kitchen_config')
    op.drop_table('kitchen_config')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_kitchen_type_type'), table_name='kitchen_type')
    op.drop_index(op.f('ix_kitchen_type_id'), table_name='kitchen_type')
    op.drop_table('kitchen_type')
    # ### end Alembic commands ###
